### ISSUE TITLE
card0 and card1 don't link to the same graphics card

### ISSUE THREAD

**Issue by r15ch13** [Eraden/amdgpud#11]
I have an NVidia and an AMD card installed and every so often the mapping in `/sys/class/drm` changes.
Sometimes `card0` is the AMD card and another time it's the NVidia card.

As a workaround I added `cards = ["card0", "card1"]` to the `config.toml`

As of now, I haven't found a way to always refer to the right card.

**Comment by Eraden** [comment]
This will b changed so you can specify list of cards or set `All`.

But if we can't rely on OS here then I'm afraid we should remove it entirely

**Comment by Eraden** [comment]
Please give me following information:

* from `/etc/default/grub` value of `GRUB_CMDLINE_LINUX_DEFAULT=`
* from `/etc/mkinitcpio.conf` value of `HOOKS=` and `MODULES=`
* output of `grep nvidia -R /etc/modprobe.d`
* output of `grep amd -R /etc/modprobe.d`
* output of `sudo lsmod | grep amdgpu`
* output of `sudo lsmod | grep nvidia`

**Comment by r15ch13** [comment]
```bash
[r15ch13@Bluescreen ~]$ cat /etc/default/grub | grep GRUB_CMDLINE_LINUX_DEFAULT=
GRUB_CMDLINE_LINUX_DEFAULT="quiet apparmor=1 security=apparmor udev.log_priority=3 amd_iommu=on"
[r15ch13@Bluescreen ~]$ cat /etc/mkinitcpio.conf | grep HOOKS=\"
HOOKS="base udev autodetect modconf block keyboard keymap filesystems fsck"
[r15ch13@Bluescreen ~]$ cat /etc/mkinitcpio.conf | grep MODULES=\"
MODULES=""
[r15ch13@Bluescreen ~]$ grep nvidia -R /etc/modprobe.d
[r15ch13@Bluescreen ~]$ grep amd -R /etc/modprobe.d
[r15ch13@Bluescreen ~]$ sudo lsmod | grep amdgpu
amdgpu               6533120  57
gpu_sched              45056  1 amdgpu
ttm                   114688  2 amdgpu,nouveau
drm_kms_helper        270336  2 amdgpu,nouveau
i2c_algo_bit           16384  3 igb,amdgpu,nouveau
drm                   569344  21 gpu_sched,drm_kms_helper,amdgpu,ttm,nouveau
[r15ch13@Bluescreen ~]$ sudo lsmod | grep nvidia
[r15ch13@Bluescreen ~]$ sudo lsmod | grep nouveau
nouveau              2334720  3
mxm_wmi                16384  1 nouveau
video                  57344  1 nouveau
ttm                   114688  2 amdgpu,nouveau
drm_kms_helper        270336  2 amdgpu,nouveau
i2c_algo_bit           16384  3 igb,amdgpu,nouveau
wmi                    36864  3 wmi_bmof,mxm_wmi,nouveau
drm                   569344  22 gpu_sched,drm_kms_helper,amdgpu,ttm,nouveau
agpgart                53248  3 ttm,nouveau,drm
[r15ch13@Bluescreen ~]$
```

![image](https://user-images.githubusercontent.com/432127/127874848-a90de3f0-090f-4ae5-bb33-013d6d72332d.png)

**Comment by Eraden** [comment]
Can you try change `/etc/mkinitcpio.conf`

```
MODULES=(amdgpu nouveau)
```

```
sudo mkinitcpio -P
```

And restart it couple times checking each time?

```
cat /sys/class/drm/card0/device/vendor
```

**Comment by r15ch13** [comment]
That seems to work. It returns `0x1002`.

**Comment by BoostCookie** [comment]
`MODULES=(amdgpu nouveau)`
Does that load the amd card always before the nvidia card?

If yes then that still only works for this specific case where a user only has a single amd card. What if somebody has multiple amd cards? Here it is still random which one gets which hwmon number.

Since we can't rely on the hwmon number the OS provides we should just take the hardcoded pci path. For example my card currently is under `/sys/class/hwmon2` which is just a symbolic link to `/sys/devices/pci0000:00/0000:00:03.1/0000:26:00.0/0000:27:00.0/0000:28:00.0/hwmon/hwmon2`.

So instead of `cards = ["card0"]` the config could specify `cards = [/sys/devices/pci0000:00/0000:00:03.1/0000:26:00.0/0000:27:00.0/0000:28:00.0/hwmon]` and the program always uses the only directory in that path.

**Comment by BoostCookie** [comment]
Also I think we should allow to specify different fan curves for different fans and as I said [here](https://github.com/Eraden/amdgpud/pull/15) we should allow to specify which temperature is relevant for any specific fan curve.

In my opinion the config file should look a little something like this:
```
hwmons = /sys/devices/pci0000:00/0000:01.0/hwmon/*/pwm1, /sys/devices/pci0000:00/0000:04.2/hwmon/*/pwm4
temp = /sys/devices/pci0000:00/0000:01.0/hwmon/*/temp1_input
14.0, 20.3
60.5, 50.0
70.0, 100.0

hwmons = /sys/devices/pci0000:00/0000:01.0/hwmon/*/pwm2, /sys/devices/pci0000:00/0001:12.0/0000:01:0.4/hwmon/*/pwm2
temp = /sys/devices/pci0000:00/0000:01.0/hwmon/*/temp2_input, /sys/devices/pci0000:00/0000:01.0/hwmon/*/temp3_input
45.0, 20.0
60.0, 40.2
65.0, 100.0
```
Each fancurve takes the max value of all its `temp` paths as temperature and applies the speed to each pwm in `hwmons`.

**Comment by r15ch13** [comment]
> `MODULES=(amdgpu nouveau)`
> Does that load the amd card always before the nvidia card?

For me, it indeed fixed the random assignment of `card0`.

**Comment by BoostCookie** [comment]
@r15ch13 So you're using the open source nouveau drivers for your nvidia card? Do they also allow writing to `pwm1` to change the fan speed?

**Comment by r15ch13** [comment]
Nope, that does not work with nouveau drivers.

![image](https://user-images.githubusercontent.com/432127/128346347-695f983a-e476-4838-998c-f5726f2e254c.png)

**Comment by Eraden** [comment]
Did you changed from automatic to manual?

**Comment by r15ch13** [comment]
I can't set `pwm1_enable` to `1` or `2`, it always returns `Invalid argument`

**Comment by Eraden** [comment]
OMG, this is on screenshot. Sorry for stupid question
