### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by lmartinez-mirror** [Eraden/amdgpud#2]
This project is missing a license file, so technically no one can use it.

You can pick one out from [here](https://choosealicense.com/).

**Comment by Eraden** [comment]
License is specified in Cargo.toml by name but you are right. It would be good to include license as a file

**Comment by Eraden** [comment]
Dual license added in:

* LICENSE
* README
* LICENSE.MIT.md
* LICENSE.APACHE2.md
