### ISSUE TITLE
Error: Kind(InvalidData)

### ISSUE THREAD

**Issue by patrykwegrzyn** [Eraden/amdgpud#24]
Hi there
I tried to follow the instruction but getting error on startup `Error: Kind(InvalidData)`

**Comment by Eraden** [comment]
Please paste `/etc/amdfand/config.toml`

**Comment by patrykwegrzyn** [comment]
`cat /etc/amdgpud/config.toml`
```
log_level = "Error"
cards = ["card0"]

[[speed_matrix]]
temp = 4.0
speed = 4

[[speed_matrix]]
temp = 30.0
speed = 33

[[speed_matrix]]
temp = 45.0
speed = 50

[[speed_matrix]]
temp = 60.0
speed = 66

[[speed_matrix]]
temp = 65.0
speed = 69

[[speed_matrix]]
temp = 70.0
speed = 75

[[speed_matrix]]
temp = 75.0
speed = 89

[[speed_matrix]]
temp = 80.0
speed = 100
```

**Comment by patrykwegrzyn** [comment]
Looks like moving config from `/etc/amdgpud/config.toml`-> `/etc/amdfand/` solves issue .
Not sure how did i get `etc/amdgpud/config.toml` in a first place, probably leftover from something i tried in the past?

**Comment by Eraden** [comment]
I'll investigate this. Also I'll improve error messages since what I have now is far from perfect.

Thanks for bug report :heart:
