### ISSUE TITLE
openrc service should not print out

### ISSUE THREAD

**Issue by BoostCookie** [Eraden/amdgpud#29]
openrc does not want the service program to print out things. There are two options:
1. In the service file we add `command_args_background="--background"` and we change the program to not print out anything when `--background` is passed
2. Just add `command_background=true` to the service file. Then openrc knows that the program isn't "well behaved" and openrc ignores the printouts

**Comment by Eraden** [comment]
Please confirm issue was fixed 🙏

**Comment by BoostCookie** [comment]
Yes it works.
