### ISSUE TITLE
Not working on Ubuntu 20 LTS

### ISSUE THREAD

**Issue by dubigrasu** [Eraden/amdgpud#3]
It needs higher version libraries than Ubuntu LTS can provide:
`./amdfand: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./amdfand)`

**Comment by Eraden** [comment]
Hi, I don't own any PC with Ubuntu 18 nor 20. I'm working on setting up GH matrix  to build, upload and attach binary for both Ubuntu but in meanwhile only way to obtain working binary is building it from clone or with `cargo install amdfand` (it'll be available in `~/.cargo/bin`.

This issue will remain open until solution for this case is implemented

**Comment by Eraden** [comment]
@dubigrasu can you please download and verify is newest [newest release](https://github.com/Eraden/amdgpud/releases/tag/1.0.4) is working for you?

**Comment by dubigrasu** [comment]
Yes, it does start now. I only tested the "monitor" feature, but it seems to be working fine.
Many thanks.

**Comment by Eraden** [comment]
I'm closing issue for now. Please reopen it if you will have any other problem on Ubuntu
