### ISSUE TITLE
Does not works on AMD Vega

### ISSUE THREAD

**Issue by Eraden** [Eraden/amdgpud#4]

**Comment by jasondaigo** [comment]
Sapphire Vega56 Pulse
Kernel 5.12.14
Arch
Fancontrol config
```

**Comment by BoostCookie** [comment]
@r15ch13 I just wanted to comment the exact same thing.
Also the default config makes it look like speed has to be a percentage between 4 and 100, but the value gets directly, without conversion, written to `pwm1` which goes from 0 to 255.
I think it would be best to keep it as a percentage from 0 to 100 (also allowing floats) in the config and then convert it to an int in the correct range.

And I'm not sure which would be better to change. Either use `pwm1_min` and `pwm1_max` for the boundaries and let `set_speed` write to `pwm1`, or use `fan1_min` and `fan1_max` for the boundaries and write to `fan1_target`. I don't know if every AMD card has both options though.
