### ISSUE TITLE
Graph axes should be swapped

### ISSUE THREAD

**Issue by Sohex** [Eraden/amdgpud#43]
I guess this is more of a nitpick than an outright issue, but the two axes of the graph should be swapped. The independent variable which is temperature belongs on the x axis and the y axis should be speed since it's dependent on temperature.

**Comment by Eraden** [comment]
I'll change this in next release

**Comment by Eraden** [comment]
Graphs swapped and Drag&Drop fixed so currently it should works much better.

When pipeline pass I'll publish AUR, cargo.io is updated
