### ISSUE TITLE
amdguid ... something is very wrong?

### ISSUE THREAD

**Issue by donaastor** [Eraden/amdgpud#48]
I installed amdguid with
```crate install amdguid```
and in the same fashion I installed amdfand, amdvold and amdmond.
I ran amdguid from my terminal, and I see a window where GUI is tiny, in top left corner and other 3 fourths are blue with a red triangle in the middle??? and my terminal is mad btw:
````
 WARN  amdguid::app > Failed to load amd fan services pid list. GuiHelper(NoSockFile)
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
 INFO  winit::platform_impl::platform::x11::window > Guessed window scale factor: 2
 DEBUG winit::platform_impl::platform::x11::window > Calculated physical dimensions: 1024x768
 WARN  amdguid::app                                > Failed to load amd fan services pid list. GuiHelper(NoSockFile)
 WARN  amdguid::app                                > Failed to load amd fan services pid list. GuiHelper(NoSockFile)
 WARN  amdguid::app                                > Failed to load amd fan services pid list. GuiHelper(NoSockFile)
 WARN  amdguid::app                                > Failed to load amd fan services pid list. GuiHelper(NoSockFile)
 WARN  amdguid::app                                > Failed to load amd fan services pid list. GuiHelper(NoSockFile)
 WARN  amdguid::app                                > Failed to load amd fan services pid list. GuiHelper(NoSockFile)
 WARN  amdguid::app                                > Failed to load amd fan services pid list. GuiHelper(NoSockFile)
...
````

**Comment by donaastor** [comment]
How exactly am I supposed to install and run this software? I am very confused...

**Comment by Eraden** [comment]
If you can give me hardware spec, kernel version and WM/DE

**Comment by donaastor** [comment]
@Eraden Sure:
Ryzen 9 5900x
RX 6650 XT
32GB RAM (no swap)
MSI MAG B550 Tomahawk
232GB nvme
4K monitor
It is linux 5.18.16.arch1-1, I am not sure how to check kernel version, sorry. I think it was some 251.14 ??? I am not sure, sorry
X.org + i3-gaps

**Comment by Eraden** [comment]
I see. You are using xorg.

Please try:

```
cargo install -f amdguid --no-default-features --features xorg-glow
```

**Comment by donaastor** [comment]
> Please try:
> 
> ```
> cargo install -f amdguid --no-default-features --features xorg-glow
> ```
Ok, thank you! I will try it later

**Comment by Eraden** [comment]
This will open GUI application. You need amdgui-helper run with root to save changes. 

You need andfand to control GPU cooling.

Both can be booted from systemd. If you need instruction how to install service files I can give it

**Comment by donaastor** [comment]
Ok, I understand that now. Currently I am fighting another issue, so I won't need any isntructions for this for next few hours, but I will appreciate very much if you give them soon. Is it simply enabling some services in systemd?

**Comment by Eraden** [comment]
It just came to me what you are having as an avatar.

As supporter of Ukraine freedom I refuse to help any Russia supporters.


No further help will be provided
Glory to Ukraine
