### ISSUE TITLE
Openrc service doesn't always start fan on a startup.

### ISSUE THREAD

**Issue by Giger22** [Eraden/amdgpud#53]
Amdfand service sometimes requires manual start (sudo amdfand in terminal) after system startup. 
I have no idea why fans sometimes start spinning and other time doesn't. 
I have this in a config file so temperature settings aren't an explanation to this problem.

[[speed_matrix]]
temp = 4.0
speed = 10.0

Services...
rc-update  -a
amdfand |      default

**Comment by Eraden** [comment]
Hi Giger22.

How many graphics card do you have?
Can you give me any system logs related to boot?

**Comment by Giger22** [comment]
I have one GPU (AMD RX 5700 XT).
Do you mean rc.conf?

This is just after startup when amdfand did not start.

rc boot logging started at Sat Dec 17 18:49:00 2022

modules           | * Loading module crypto_user ...
termencoding      | * Setting terminal encoding [UTF-8] ...
 [ ok ]
modules           | * Loading module sg ...
 [ ok ]
keymaps           | * Setting keyboard mode [UTF-8] ...
 [ ok ]
keymaps           | * Loading key mappings [us] ...
 [ ok ]
 [ ok ]
modules           | * Loading module vboxdrv ...
modules           | * Failed to load vboxdrv
 [ !! ]
modules           | * Loading module vboxnetadp ...
modules           | * Failed to load vboxnetadp
 [ !! ]
modules           | * Loading module vboxnetflt ...
modules           | * Failed to load vboxnetflt
 [ !! ]
hwclock           | * Setting system clock using the hardware clock [UTC] ...
hwclock           |grep: warning: stray \ before -
hwclock           |grep: warning: stray \ before -
 [ ok ]
loopback          | * Bringing up network interface lo ...
hostname          | * Setting hostname to art from /etc/hostname ...
 [ ok ]
fsck              | * Checking local filesystems  ...
procfs            | * Mounting misc binary format filesystem ...
sysctl            | * Configuring kernel parameters ...
 [ ok ]
 [ ok ]
 [ ok ]
 [ ok ]
root              | * Remounting filesystems ...
 [ ok ]
binfmt            | * Loading custom binary format handlers ...
 [ ok ]
swap              | * Activating swap devices ...
mtab              | * Updating /etc/mtab ...
 [ ok ]
mtab              | * Creating mtab symbolic link
 [ ok ]
localmount        | * Mounting local filesystems ...
 [ ok ]
opensysusers      | * Setting up sysusers.d entries ...
seedrng           | * Seeding random number generator ...
opentmpfiles-setup| * Setting up tmpfiles.d entries ...
seedrng           | * Seeding 256 bits and crediting
seedrng           | * Saving 256 bits of creditable seed for next boot
 [ ok ]
 [ ok ]
bootmisc          | * Creating user login records ...
 [ ok ]
bootmisc          | * Wiping /tmp directory ...
 [ ok ]
 [ ok ]
net.lo            | * Bringing up interface lo
net.lo            | *   Caching network module dependencies
consolefont       | * Setting console font [default8x16] ...
save-termencoding | * Saving terminal encoding ...
save-keymaps      | * Saving key mapping ...
dbus              | * Starting dbus ...
 [ ok ]
 [ ok ]
 [ ok ]
elogind           | * Starting elogind ...
 [ ok ]
 [ ok ]
NetworkManager    | * Starting NetworkManager ...
 [ ok ]
net.lo            | *   127.0.0.1/8 ...
 [ ok ]
net.lo            | *   Adding routes
net.lo            | *     127.0.0.0/8 via 127.0.0.1 ...
 [ ok ]
 [ ok ]
NetworkManager    |Connecting.                  1sConnecting..                 1sConnecting...                1sConnecting....               1sConnecting.....              1sConnecting......             1sConnecting.......            1sConnecting........           1sConnecting.........          1sConnecting..........         1sConnecting...........        1sConnecting............       1sConnecting.............      1sConnecting..............     1sConnecting...............    1sConnecting...............    0s [offline]
NetworkManager    | * Marking NetworkManager as inactive. It will automatically be marked
NetworkManager    | * as started after a network connection has been established.
opensnitchd       | * WARNING: opensnitchd will start when NetworkManager has started
NetworkManager    | * WARNING: NetworkManager has started, but is inactive

rc boot logging stopped at Sat Dec 17 18:49:02 2022


rc default logging started at Sat Dec 17 18:49:02 2022

openrc-settingsd  | * Stopping openrc-settingsd ...
 [ ok ]
netmount          | * WARNING: netmount will start when NetworkManager has started
opensnitchd       | * WARNING: opensnitchd will start when NetworkManager has started
amdmond           | * Starting amdmond ...
amdfand           | * Starting amdfand ...
amdmond           | * start-stop-daemon: `/var/log/amdmon.csv' is not a valid signal
amdmond           | * Failed to start amdmond
 [ !! ]
amdmond           | * ERROR: amdmond failed to start
 [ ok ]
avahi-daemon      | * Starting avahi-daemon ...
bluetoothd        | * Starting bluetoothd ...
portmaster        | * Starting portmaster ...
amdgui-helper     | * Starting amdgui-helper ...
sddm              | * Starting sddm ...
syslog-ng         | * Checking your configfile (/etc/syslog-ng/syslog-ng.conf) ...
docker            | * Starting docker ...
 [ ok ]
 [ ok ]
 [ ok ]
 [ ok ]
 [ ok ]
 [ ok ]
 [ ok ]
syslog-ng         | * Starting syslog-ng ...
 [ ok ]
clamd             | * Starting clamd ...
acpid             | * Starting acpid ...
ntp-client        | * Setting clock via the NTP client 'ntpdate' ...
ntp-client        |Exiting, name server cannot be used: Temporary failure in name resolution (-3) [ ok ]
 * Failed to set clock
 [ !! ]
ntp-client        | * ERROR: ntp-client failed to start
cupsd             | * Starting cupsd ...
 [ ok ]
cronie            | * Starting cronie ...
 [ ok ]
agetty.tty2       | * agetty.tty2: waiting for clamd (50 seconds)
agetty.tty6       | * agetty.tty6: waiting for clamd (50 seconds)
agetty.tty1       | * agetty.tty1: waiting for clamd (50 seconds)
agetty.tty3       | * agetty.tty3: waiting for clamd (50 seconds)
agetty.tty4       | * agetty.tty4: waiting for clamd (50 seconds)
local             | * local: waiting for clamd (50 seconds)
agetty.tty5       | * agetty.tty5: waiting for clamd (50 seconds)
 [ ok ]
clamd             | * Starting freshclam ...
 [ ok ]
local             | * Starting local ...
 [ ok ]

rc default logging stopped at Sat Dec 17 18:49:14 2022

**Comment by Giger22** [comment]
Btw  I can't start amdmond.
art:[art]:~$ sudo rc-service amdmond start
amdmond           | * Starting amdmond ...
amdmond           | * start-stop-daemon: `/var/log/amdmon.csv' is not a valid signal
amdmond           | * Failed to start amdmond                                                                                                                                                               [ !! ]
amdmond           | * ERROR: amdmond failed to start

**Comment by Giger22** [comment]
Ok, I had to reinstall my system and it seems that fans start every single time.
