### ISSUE TITLE
 ERROR amdgpu_config::fan > Curve fan temps should be monotonically increasing, found 70 then 60

### ISSUE THREAD

**Issue by TornaxO7** [Eraden/amdgpud#57]
I'm getting the following error message if I run:
```bash
sudo amdguid
```
output:
```bash
 ERROR amdgpu_config::fan > Curve fan temps should be monotonically increasing, found 70 then 60
thread 'main' panicked at 'No FAN config: UnsortedFanTemp { current: 60.0, index: 8, last: 70.0 }', amdguid/src/main.rs:22:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
may I ask what I should do here?

I'm running arch linux, the `amdgui-helper.service` is enabled and running.

**Comment by Eraden** [comment]
It appears that your config file contains bad data. Please edit or delete it.

If you are familiar with nano or vim please use one of the following command:

```
vim /etc/amdfand/config.toml
nano /etc/amdfand/config.toml
```

Then find config line with non monotonic values (example 70 then 60) and remove them

If you will have any issues please don't hesitate to contact me here or via email adrian.wozniak@ita-prog.pl or via Matrix etaden (kind there's t instead t, eraden was taken)

Yours sincerely
Eraden

**Comment by TornaxO7** [comment]
Thank you for the quick answer! I could find a weird-order and removed it but I can't test it currently. I'll reopen this, if there will be some other problems. Thank you.
