### ISSUE TITLE
amdfand-bin: local (1.0.13-4) is newer than AUR (1.0.11-2)

### ISSUE THREAD

**Issue by bitterhalt** [Eraden/amdgpud#63]
I get this message every time update my packages with yay or paru:
`
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 multilib is up to date
:: Searching AUR for updates...
:: Searching databases for updates...
 -> amdfand-bin: local (1.0.13-4) is newer than AUR (1.0.11-2)
`

I guess it is problem with AUR package but is there anyway to fix that?

**Comment by bitterhalt** [comment]
Not Eradens problem so I am closing this

**Comment by Eraden** [comment]
Hi, I'm sorry for not responding. Unfortunately I don't have too much time right now for working on this project. I'm half way in creating pipeline with drone.io to solve the issue but it may take time. Sorry again for inconvenience
