### ISSUE TITLE
Unable to install amdfand v1.0.12-1 on arch linux

### ISSUE THREAD

**Issue by winstonrc** [Eraden/amdgpud#67]
I am having issues installing and building amdfand version 1.0.12-1 from the [aur](https://aur.archlinux.org/packages/amdfand) on my arch linux build.

When updating the package, I run into the following error message:

```bash
   Compiling unwinding v0.2.1
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /tmp/makepkg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/unwinding-0.2.1/src/lib.rs:2:1
  |
2 | #![feature(c_unwind)]
  | ^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /tmp/makepkg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/unwinding-0.2.1/src/lib.rs:3:1
  |
3 | #![feature(naked_functions)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /tmp/makepkg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/unwinding-0.2.1/src/lib.rs:4:1
  |
4 | #![feature(non_exhaustive_omitted_patterns_lint)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `unwinding` (lib) due to 3 previous errors
```

My setup:

```
Kernel: 6.7.0-arch3-1
DE: Plasma 5.27.10
```

**Comment by erenard** [comment]
I can confirm the problem on the AUR package `amdfand`.
```
   Compiling unwinding v0.2.1
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /home/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/unwinding-0.2.1/src/lib.rs:2:1
  |
2 | #![feature(c_unwind)]
  | ^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /home/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/unwinding-0.2.1/src/lib.rs:3:1
  |
3 | #![feature(naked_functions)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /home/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/unwinding-0.2.1/src/lib.rs:4:1
  |
4 | #![feature(non_exhaustive_omitted_patterns_lint)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `unwinding` (lib) due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
==> ERREUR : Une erreur s’est produite dans build().
    Abandon…
```

**Comment by erenard** [comment]
Here is a workaround:
```
> curl https://github.com/eraden.gpg | gpg --import
> pamac install amdgpud
```

**Comment by jahtnamas** [comment]
that doesn't really fix installing the version of amdfand that OP mentions, but i guess it _technically_ solves the inability to install that update by changing out the version of amdfand with the entire amdgpud suite of the same version that was orphaned and won't update.

thanks? ...yeah, thanks.

**Comment by Eraden** [comment]
Hi, this issue originate in rust version used to build crate. For some reason, and I don't know how to fix it, pamac is using stable rust but project requires nightly to be compiled correctly.

I'm not the maintainer of this AUR package so I can't fix it. I also don't have too much time right now since I have now 2 small kids and my hands are too occupied in this project.

If we have here maintainer of AUR package please try following:

```
cargo +nightly build --frozen --release --bin amdfand
```

**Comment by winstonrc** [comment]
Thanks for the insight and for creating this useful tool! I see that you commented on the AUR page as well, so hopefully the maintainer follows your tip and it fixes the issue.

I'll leave this issue open for now in case others come here looking for a similar resolution and then close it if/when the package is working again.

**Comment by yochananmarqos** [comment]
1.0.12 doesn't compile with the latest nightly toolchain, either:

```
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2024-02-26, rust version 1.78.0-nightly (0ecbd0605 2024-02-25)
```

```
error[E0635]: unknown feature `stdsimd`
  --> /build/amdgpud/src/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.7.7/src/lib.rs:33:42
   |
33 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^

For more information about this error, try `rustc --explain E0635`.
error: could not compile `ahash` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by winstonrc** [comment]
> error[E0635]: unknown feature `stdsimd`

This appears to be due to the ahash dependency, with the fix implemented here: https://github.com/tkaitchuck/aHash/pull/183

**Comment by Eraden** [comment]
I'm trying to update egui but Emik changed a lot and there's no support for glium/glow so it must be now rewritten to wgpu

**Comment by winstonrc** [comment]
That's definitely an undertaking. I'd love to help, but I think it would take me awhile to get up to speed with the repo and libraries.

Maybe this repo would be a helpful reference for you: https://github.com/ejb004/egui-wgpu-demo

**Comment by winstonrc** [comment]
Thanks so much @Eraden. It's now compiling. I'll go ahead and close this issue since the package on aur is a matter of the new maintainer updating it.
